### ISSUE TITLE
Option to remove type attribute in link preload

### ISSUE THREAD

**Issue by rwv** [Applelo/vite-plugin-inject-preload#11]
Thank you for this wonderful plugin! Can you provide a option to disable `type="application/javascript"`?

**Comment by rwv** [comment]
FYI, the code below generates `type=undefined`
```
attributes: {
  type: undefined,
},
```

**Comment by Applelo** [comment]
Thanks for the issue, currently I force the type but you right with this issue, this is not a required attribute, just a recommended one.
I will look into that to make sure we can disable the type qttribute and provide some test to ensure everything is working properly.
